AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - ".git/**/*"
    - "gemfiles/*"
  NewCops: enable

#
# RuboCop built-in settings.
#   For documentation on all settings see: https://docs.rubocop.org/en/stable
#

# Turn on auto-correction of equals alignment.
Layout/EndAlignment:
  AutoCorrect: true

# Prevent accidental windows line endings
Layout/EndOfLine:
  EnforcedStyle: lf

# Use a table layout for hashes
Layout/HashAlignment:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table

# Match existing layout
Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

# Support long block lengths for tests
Metrics/BlockLength:
  Exclude:
    - "test/**/*"

# Initialization Vector abbreviation
Naming/MethodParameterName:
  AllowedNames: ['iv', '_', 'io', 'ap']

# Does not allow Symbols to load
Security/YAMLLoad:
  AutoCorrect: false

# Needed for testing DateTime
Style/DateTime:
  Exclude: ["test/**/*"]

Style/Documentation:
  Enabled: false

# One line methods
Style/EmptyMethod:
  EnforcedStyle: expanded

Style/NumericPredicate:
  AutoCorrect: true

# Since English may not be loaded, cannot force its use.
Style/SpecialGlobalVars:
  Enabled: false

# Match Rails
Style/StringLiterals:
  EnforcedStyle: double_quotes
